export const listsAge = [
    { codeValue: '0', name: '0~5' },
    { codeValue: '6', name: '6~7' },
    { codeValue: '8', name: '8~13' },
    { codeValue: '14', name: '14~19' },
    { codeValue: '20', name: '20대' },
    { codeValue: '30', name: '30대' },
    { codeValue: '40', name: '40대' },
    { codeValue: '50', name: '50대' },
    { codeValue: '60', name: '60대 이상' }
];

export const listsGender = [
    { codeValue: '0', name: '남성'},
    { codeValue: '1', name: '여성'},
]

export const listsDtlKdc = [
    { codeValue: '00', name: '총류' },
    { codeValue: '01', name: '도서학, 서지학' },
    { codeValue: '02', name: '문헌정보학' },
    { codeValue: '03', name: '백과사전' },
    { codeValue: '04', name: '일반 논문집' },
    { codeValue: '05', name: '일반 연속간행물' },
    { codeValue: '06', name: '학·협회 기관' },
    { codeValue: '07', name: '신문, 언론, 저널리즘' },
    { codeValue: '08', name: '일반 전집, 총서' },
    { codeValue: '09', name: '향토자료' },
    { codeValue: '10', name: '철학' },
    { codeValue: '11', name: '형이상학' },
    { codeValue: '12', name: '인식론, 인과론, 인간학' },
    { codeValue: '13', name: '철학의 체계' },
    { codeValue: '14', name: '경학' },
    { codeValue: '15', name: '동양 철학, 사상' },
    { codeValue: '16', name: '서양철학' },
    { codeValue: '17', name: '논리학' },
    { codeValue: '18', name: '심리학' },
    { codeValue: '19', name: '윤리학, 도덕철학' },
    { codeValue: '20', name: '종교' },
    { codeValue: '21', name: '비교종교학' },
    { codeValue: '22', name: '불교' },
    { codeValue: '23', name: '기독교' },
    { codeValue: '24', name: '도교' },
    { codeValue: '25', name: '천도교' },
    { codeValue: '26', name: '신도' },
    { codeValue: '27', name: '바라문교, 인도교' },
    { codeValue: '28', name: '회교(이슬람교)' },
    { codeValue: '29', name: '기타 제종교' },
    { codeValue: '30', name: '사회과학' },
    { codeValue: '31', name: '통계학' },
    { codeValue: '32', name: '경제학' },
    { codeValue: '33', name: '사회학, 사회문제' },
    { codeValue: '34', name: '정치학' },
    { codeValue: '35', name: '행정학' },
    { codeValue: '36', name: '법학' },
    { codeValue: '37', name: '교육학' },
    { codeValue: '38', name: '풍속, 민속학' },
    { codeValue: '39', name: '국방, 군사학' },
    { codeValue: '40', name: '자연과학' },
    { codeValue: '41', name: '수학' },
    { codeValue: '42', name: '물리학' },
    { codeValue: '43', name: '화학' },
    { codeValue: '44', name: '천문학' },
    { codeValue: '45', name: '지학' },
    { codeValue: '46', name: '광물학' },
    { codeValue: '47', name: '생물과학' },
    { codeValue: '48', name: '식물학' },
    { codeValue: '49', name: '동물학' },
    { codeValue: '50', name: '기술과학' },
    { codeValue: '51', name: '의학' },
    { codeValue: '52', name: '농업, 농학' },
    { codeValue: '53', name: '공학, 공업일반' },
    { codeValue: '54', name: '건축공학' },
    { codeValue: '55', name: '기계공학' },
    { codeValue: '56', name: '전기공학, 전자공학' },
    { codeValue: '57', name: '화학공학' },
    { codeValue: '58', name: '제조업' },
    { codeValue: '59', name: '가정학 및 가정생활' },
    { codeValue: '60', name: '예술' },
    { codeValue: '61', name: '건축술' },
    { codeValue: '62', name: '조각' },
    { codeValue: '63', name: '공예, 장식미술' },
    { codeValue: '64', name: '서예' },
    { codeValue: '65', name: '회화, 도화' },
    { codeValue: '66', name: '사진술' },
    { codeValue: '67', name: '음악' },
    { codeValue: '68', name: '연극' },
    { codeValue: '69', name: '오락, 운동' },
    { codeValue: '70', name: '언어' },
    { codeValue: '71', name: '한국어' },
    { codeValue: '72', name: '중국어' },
    { codeValue: '73', name: '일본어' },
    { codeValue: '74', name: '영어' },
    { codeValue: '75', name: '독일어' },
    { codeValue: '76', name: '프랑스어' },
    { codeValue: '77', name: '스페인어' },
    { codeValue: '78', name: '이탈리아어' },
    { codeValue: '79', name: '기타 제어' },
    { codeValue: '80', name: '문학' },
    { codeValue: '81', name: '한국문학' },
    { codeValue: '82', name: '중국문학' },
    { codeValue: '83', name: '일본문학' },
    { codeValue: '84', name: '영미문학' },
    { codeValue: '85', name: '독일문학' },
    { codeValue: '86', name: '프랑스문학' },
    { codeValue: '87', name: '스페인문학' },
    { codeValue: '88', name: '이탈리아문학' },
    { codeValue: '89', name: '기타 제문학' },
    { codeValue: '90', name: '역사' },
    { codeValue: '91', name: '아시아(아세아)' },
    { codeValue: '92', name: '유럽(구라파)' },
    { codeValue: '93', name: '아프리카' },
    { codeValue: '94', name: '북아메리카(북미)' },
    { codeValue: '95', name: '남아메리카(남미)' },
    { codeValue: '96', name: '오세아니아(대양주)' },
    { codeValue: '97', name: '양극지방' },
    { codeValue: '98', name: '지리' },
    { codeValue: '99', name: '전기' }
];

export const listsRegion = [
    { codeValue: '11', name: '서울' },
    { codeValue: '21', name: '부산' },
    { codeValue: '22', name: '대구' },
    { codeValue: '23', name: '인천' },
    { codeValue: '24', name: '광주' },
    { codeValue: '25', name: '대전' },
    { codeValue: '26', name: '울산' },
    { codeValue: '29', name: '세종' },
    { codeValue: '31', name: '경기' },
    { codeValue: '32', name: '강원' },
    { codeValue: '33', name: '충북' },
    { codeValue: '34', name: '충남' },
    { codeValue: '35', name: '전북' },
    { codeValue: '36', name: '전남' },
    { codeValue: '37', name: '경북' },
    { codeValue: '38', name: '경남' },
    { codeValue: '39', name: '제주' }
];


